#!/usr/bin/env python3
import sys

def usage():
    print("USAGE")
    print("    ./201yams d1 d2 d3 d4 d5 c\n")
    print("DESCRIPTION")
    print("    d1    value of the first die (0 if not thrown)")
    print("    d2    value of the second die (0 if not thrown)")
    print("    d3    value of the third die (0 if not thrown)")
    print("    d4    value of the fourth die (0 if not thrown)")
    print("    d5    value of the fifth die (0 if not thrown)")
    print("    c     expected combination")
    exit(0)

def checkArgs():
    for i in range (1, 6):
        if (int(sys.argv[i]) < 0 or int(sys.argv[i]) > 6):
            exit(84)
    combineArray = ["pair", "three", "four", "straight", "yams"]
    expected = sys.argv[6].split('_')
    if (len(expected) == 2):
        if (expected[0] not in combineArray):
            exit(84)
        if (int(expected[1]) < 1 or int(expected[1]) > 6):
            exit(84)
    if (len(expected) == 3):
        if (expected[0] != "full"):
            exit(84)
        if ((int(expected[1]) < 1 or int(expected[1]) > 6) or (int(expected[2]) < 1 or int(expected[2]) > 6)):
            exit(84)
    if (len(expected) < 2 or len(expected) > 3):
        exit(84)

def errorHandling():
    if (len(sys.argv) == 2):
        if (sys.argv[1] == '-h'):
            usage()
        exit(84)
    if (len(sys.argv) != 7):
        exit(84)
    checkArgs()

def pair(nbrArray: list, combine: list):
    if (nbrArray.count(int(combine[1])) >= 2):
        print("Chances to get a " + str(combine[1]) + " pair: 100.00%")

def three(nbrArray: list, combine: list):
    if (nbrArray.count(int(combine[1])) >= 3):
        print("Chances to get a " + str(combine[1]) + " three-of-a-kind: 100.00%")

def four(nbrArray: list, combine: list):
    if (nbrArray.count(int(combine[1])) >= 4):
        print("Chances to get a " + str(combine[1]) + " four-of-a-kind: 100.00%")

def straight(nbrArray: list, combine: list):
    smallNbr = min(nbrArray)
    maxNbr = smallNbr + 4
    while (smallNbr != maxNbr):
        if (nbrArray.count(smallNbr) == 1):
            smallNbr += 1
        else:
            break
    if (smallNbr == maxNbr):
        print("Chances to get a " + str(combine[1]) + " yahtzee: 100.00%")

def full(nbrArray: list, combine: list):
    if ((nbrArray.count(int(combine[1])) == 2 and nbrArray.count(int(combine[2])) == 3) or (nbrArray.count(int(combine[1])) == 3 and nbrArray.count(int(combine[2])) == 2)):
        print("Chances to get a " + str(combine[1]) + " full of " + str(combine[2]) + ": 100.00%")

def yams(nbrArray: list, combine: list):
    if (nbrArray.count(int(combine[1])) == 5):
        print("Chances to get a " + str(combine[1]) + " yahtzee: 100.00%")

def compute(nbrArray: list, combine: list):
    if (combine[0] == "pair"):
        pair(nbrArray, combine)
    if (combine[0] == "three"):
        three(nbrArray, combine)
    if (combine[0] == "four"):
        four(nbrArray, combine)
    if (combine[0] == "full"):
        full(nbrArray, combine)
    if (combine[0] == "yams"):
        yams(nbrArray, combine)

def main():
    errorHandling()
    nbrArray = []
    for i in range (1, 6):
        nbrArray.append(int(sys.argv[i]))
    combine = sys.argv[6].split('_')
    compute(nbrArray, combine)

if __name__ == "__main__":
    main()