#!/usr/bin/env python3

import sys
import math

def usage():
    print("USAGE")
    print("    ./202unsold a b\n")
    print("DESCRIPTION")
    print("    a    constant computed from past results")
    print("    b    constant computed from past results")

def checkArgs():
    try:
        a = int(sys.argv[1])
        b = int(sys.argv[2])
    except(ValueError):
        exit(84)

def errorHandling():
    if (len(sys.argv) == 2):
        if (sys.argv[1] == '-h'):
            usage()
        exit(84)
    if (len(sys.argv) != 3):
        exit(84)
    checkArgs()

def main():
    errorHandling()
    print("--------------------------------------------------------------------------------")

if __name__ == "__main__":
    main()