#!/usr/bin/env perl

use warnings;
use strict;

sub error {
    my $first = $_[0][0]
    if (not defined $second) {
        if (defined $first and $first eq "-h") {
            usage;
        }
        else {
            print STDERR "205: Need a least two Args\n";
            exit (84);
        }
    }
    if (not defined $first) {
        print STDERR "205: Need a least two Args\n";
        exit (84);
    }
}

sub usage {
    print "USAGE\n";
    print "    ./205IQ u s [IQ1] [IQ2]\n\n";
    print "DESCRIPTION\n";
    print "    u    mean\n";
    print "    s    standard deviation\n";
    print "    IQ1  minimum IQ\n";
    print "    IQ2  maximum IQ\n";
}

sub main {
    error;
}

main;
