/*
** EPITECH PROJECT, 2022
** bomberman
** File description:
** KeyboardMap
*/

#include "KeyboardBind.hpp"

const std::unordered_map<KeyboardKey, std::string> keyToStringMap {
    std::make_pair(KEY_A, "LETTER_A"),
    std::make_pair(KEY_B, "LETTER_B"),
    std::make_pair(KEY_C, "LETTER_C"),
    std::make_pair(KEY_D, "LETTER_D"),
    std::make_pair(KEY_E, "LETTER_E"),
    std::make_pair(KEY_F, "LETTER_F"),
    std::make_pair(KEY_G, "LETTER_G"),
    std::make_pair(KEY_H, "LETTER_H"),
    std::make_pair(KEY_I, "LETTER_I"),
    std::make_pair(KEY_J, "LETTER_J"),
    std::make_pair(KEY_K, "LETTER_K"),
    std::make_pair(KEY_L, "LETTER_L"),
    std::make_pair(KEY_M, "LETTER_M"),
    std::make_pair(KEY_N, "LETTER_N"),
    std::make_pair(KEY_O, "LETTER_O"),
    std::make_pair(KEY_P, "LETTER_P"),
    std::make_pair(KEY_Q, "LETTER_Q"),
    std::make_pair(KEY_R, "LETTER_R"),
    std::make_pair(KEY_S, "LETTER_S"),
    std::make_pair(KEY_T, "LETTER_T"),
    std::make_pair(KEY_U, "LETTER_U"),
    std::make_pair(KEY_V, "LETTER_V"),
    std::make_pair(KEY_W, "LETTER_W"),
    std::make_pair(KEY_X, "LETTER_X"),
    std::make_pair(KEY_Y, "LETTER_Y"),
    std::make_pair(KEY_Z, "LETTER_Z"),
    std::make_pair(KEY_ZERO, "NUMBER_0"),
    std::make_pair(KEY_ONE, "NUMBER_1"),
    std::make_pair(KEY_TWO, "NUMBER_2"),
    std::make_pair(KEY_THREE, "NUMBER_3"),
    std::make_pair(KEY_FOUR, "NUMBER_4"),
    std::make_pair(KEY_FIVE, "NUMBER_5"),
    std::make_pair(KEY_SIX, "NUMBER_6"),
    std::make_pair(KEY_SEVEN, "NUMBER_7"),
    std::make_pair(KEY_EIGHT, "NUMBER_8"),
    std::make_pair(KEY_NINE, "NUMBER_9"),
    std::make_pair(KEY_UP, "ARROW_UP"),
    std::make_pair(KEY_DOWN, "ARROW_DOWN"),
    std::make_pair(KEY_LEFT, "ARROW_LEFT"),
    std::make_pair(KEY_RIGHT, "ARROW_RIGHT"),
    std::make_pair(KEY_SPACE, "SPACE"),
};

const std::unordered_map<KeyboardKey, std::string> keyToGameText {
    std::make_pair(KEY_A, "A"),
    std::make_pair(KEY_B, "B"),
    std::make_pair(KEY_C, "C"),
    std::make_pair(KEY_D, "D"),
    std::make_pair(KEY_E, "E"),
    std::make_pair(KEY_F, "F"),
    std::make_pair(KEY_G, "G"),
    std::make_pair(KEY_H, "H"),
    std::make_pair(KEY_I, "I"),
    std::make_pair(KEY_J, "J"),
    std::make_pair(KEY_K, "K"),
    std::make_pair(KEY_L, "L"),
    std::make_pair(KEY_M, "M"),
    std::make_pair(KEY_N, "N"),
    std::make_pair(KEY_O, "O"),
    std::make_pair(KEY_P, "P"),
    std::make_pair(KEY_Q, "Q"),
    std::make_pair(KEY_R, "R"),
    std::make_pair(KEY_S, "S"),
    std::make_pair(KEY_T, "T"),
    std::make_pair(KEY_U, "U"),
    std::make_pair(KEY_V, "V"),
    std::make_pair(KEY_W, "W"),
    std::make_pair(KEY_X, "X"),
    std::make_pair(KEY_Y, "Y"),
    std::make_pair(KEY_Z, "Z"),
    std::make_pair(KEY_ZERO, "0"),
    std::make_pair(KEY_ONE, "1"),
    std::make_pair(KEY_TWO, "2"),
    std::make_pair(KEY_THREE, "3"),
    std::make_pair(KEY_FOUR, "4"),
    std::make_pair(KEY_FIVE, "5"),
    std::make_pair(KEY_SIX, "6"),
    std::make_pair(KEY_SEVEN, "7"),
    std::make_pair(KEY_EIGHT, "8"),
    std::make_pair(KEY_NINE, "9"),
    std::make_pair(KEY_UP, "^"),
    std::make_pair(KEY_DOWN, "v"),
    std::make_pair(KEY_LEFT, "<"),
    std::make_pair(KEY_RIGHT, ">"),
    std::make_pair(KEY_SPACE, "_"),
};